# Generated by Django 3.1.6 on 2021-02-18 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_name', models.CharField(max_length=100, verbose_name='Report Name')),
                ('create_at', models.DateTimeField(verbose_name='Time')),
                ('created_by', models.CharField(max_length=100, verbose_name='Created By')),
                ('generated_url', models.CharField(max_length=200, verbose_name='Generated URL')),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(max_length=100, verbose_name='Alert Type')),
                ('alert_name', models.CharField(max_length=100, verbose_name='Alert Name')),
                ('priorty', models.CharField(max_length=100, verbose_name='Priorty')),
                ('malaware_family', models.CharField(max_length=100, verbose_name='Malaware Family')),
                ('http_hostname', models.CharField(max_length=200, verbose_name='HTTP Hostname')),
                ('attack_reference', models.CharField(max_length=50, verbose_name='Attack Reference')),
                ('src_hostname', models.CharField(max_length=100, verbose_name='Source Hostname')),
                ('src_ip', models.CharField(max_length=50, verbose_name='Source IP')),
                ('dst_ip', models.CharField(max_length=50, verbose_name='Destination IP')),
                ('dst_country', models.CharField(max_length=100, verbose_name='Destination Country')),
                ('time', models.DateTimeField(verbose_name='Time')),
                ('reference_url', models.CharField(max_length=200, verbose_name='Reference URL')),
                ('src_country', models.CharField(max_length=100, verbose_name='Source Country')),
                ('dst_hostname', models.CharField(max_length=100, verbose_name='Destination Hostname')),
                ('recommendation', models.TextField(verbose_name='Recommendation')),
                ('description', models.TextField(verbose_name='Description')),
                ('other_tls_subject', models.CharField(max_length=255, verbose_name='Other TLS Subject')),
                ('other_tls_fingerprint', models.CharField(max_length=255, verbose_name='Other TLS Fingerprint')),
                ('other_username', models.CharField(max_length=100, verbose_name='Other Username')),
                ('other_source_nt_domain', models.CharField(max_length=100, verbose_name='Other source NT domain')),
                ('other_destination_asset', models.CharField(max_length=100, verbose_name='Other destination asset')),
                ('other', models.CharField(max_length=100, verbose_name='Other')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.report')),
            ],
        ),
    ]
