# Generated by Django 3.1.6 on 2021-02-18 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
