# Generated by Django 3.1.4 on 2020-12-09 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='time',
            field=models.CharField(max_length=30, verbose_name='Time'),
        ),
    ]
