# Generated by Django 3.1.6 on 2021-02-19 18:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_auto_20210218_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='time',
            field=models.CharField(max_length=100, verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='report',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Time'),
        ),
    ]
