# Generated by Django 3.1.4 on 2020-12-09 14:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 9, 21, 14, 32, 724256), verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='article',
            name='featured',
            field=models.BooleanField(default=False, verbose_name='Featured?'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image_url',
            field=models.FileField(upload_to='uploads/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='article',
            name='modify_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 9, 21, 14, 32, 724256), verbose_name='Last Modified'),
        ),
        migrations.AlterField(
            model_name='article',
            name='published',
            field=models.BooleanField(default=False, verbose_name='Publushed?'),
        ),
    ]
