# Generated by Django 3.1.4 on 2020-12-09 15:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20201209_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 9, 22, 44, 15, 784881), verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='article',
            name='modify_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 9, 22, 44, 15, 784881), verbose_name='Last Modified'),
        ),
    ]
