# Generated by Django 3.1.6 on 2021-02-18 15:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210218_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 18, 22, 42, 55, 362165), verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='article',
            name='modify_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 18, 22, 42, 55, 362165), verbose_name='Last Modified'),
        ),
    ]
